package gitlet;

import java.io.File;
import java.io.Serializable;

public class Blob implements Serializable {

    /** FILEID is the SHA1-Hash ID generated by the file name. */
    private String fileID;

    /** Byte[] of the contents of the file. */
    private byte[] byteFile;

    /** FILENAME is the name of the file. */
    private String fileName;

    public Blob(File file) {
        fileName = file.getName();
        byteFile = Utils.readContents(file);
        fileID = generateBlobID();
    }

    /** Returns the String SHA1-Hash ID of the current Blob. */
    public String getBlobID() {
        return fileID;
    }

    /** Returns a byte[] file of the current Blob. */
    public byte[] getFile() {
        return byteFile;
    }

    /** Returns the name of the file. */
    public String getFileName() {
        return fileName;
    }

    public String generateBlobID() {
        return Utils.sha1(fileName, byteFile);
    }

}
